/** Frozen v1 defaults. Pack digests are resolved by the server and preserved on copy/rematch. */
export const PORTFOLIO_DEFAULTS:Record<string,Record<string,unknown>>={
 'closest-call':{rounds:5,selection_seconds:20,result_seconds:3,hints:'on',hint_budget:2,max_players:20,pack_id:'closest-museum-v1'},
 'word-forge':{rounds:3,rack_size:8,selection_seconds:40,result_seconds:4,hints:'on',hint_budget:1,max_players:20,pack_id:'word-workshop-en-v1'},
 'prism-lines':{rows:5,columns:5,connect_length:4,turn_seconds:15,result_seconds:3,hints:'on',hint_budget:2,min_players:2,max_players:2},
 'relic-auction':{rounds:5,selection_seconds:20,result_seconds:4,starting_credits:100,set_bonus:30,hints:'on',hint_budget:2,min_players:2,max_players:8},
 'atlas-quest':{rounds:5,selection_seconds:25,result_seconds:4,hints:'on',hint_budget:2,max_players:20,pack_id:'atlas-world-v1',grid_columns:36,grid_rows:18,hint_score_penalty:100},
}
export const isPortfolio=(id:string)=>id in PORTFOLIO_DEFAULTS
export function portfolioDuration(id:string,rules:Record<string,any>){return id==='prism-lines'?Number(rules.rows)*Number(rules.columns)*Number(rules.turn_seconds)+Number(rules.result_seconds):Number(rules.rounds)*(Number(rules.selection_seconds)+Number(rules.result_seconds))}
export const PORTFOLIO_GAMES=[
 {id:'closest-call',name:'Closest Call',category:'Estimation',mode:'Estimate & discover',color:'#ffb543',ink:'#433315',description:'Seal a museum estimate. Discover how close your eye can get.',instructions:'Inspect the exhibit, type one integer estimate and lock it. All choices stay sealed until the fixed deadline. Scores depend on error within the range, with no speed bonus. At least one estimate within 20% qualifies for rewards. Equal scores use the seeded tie order.'},
 {id:'word-forge',name:'Word Forge',category:'Word puzzle',mode:'Build & lock',color:'#6758dc',ink:'#fff8e6',description:'Glowing letters. One strong English word. Make your rack count.',instructions:'Tap letters or type a word from the public rack. Lock once; dictionary validity and scores appear at the deadline. Valid words score 100 times length squared plus 25 per Q, Z, J or X. A sorted-rack hint is available once per match. Equal scores use the seeded tie order.'},
 {id:'prism-lines',name:'Prism Lines',category:'Board strategy',mode:'Two players · connect four',color:'#49dbbe',ink:'#204239',description:'Drop a crystal. Plan your line. Play a thoughtful garden duel.',instructions:'Two players take turns dropping a crystal into a nonfull column. Connect four in any direction to win. Two consecutive missed own turns forfeit, provided the rival has made a legal drop. Draws and idle matches pay nobody. Starting seats are seeded.'},
 {id:'atlas-quest',name:'Atlas Quest',category:'Geography',mode:'Pin & learn',color:'#3ba9ee',ink:'#163b52',description:'A place, a map, a pin. Explore the world one reveal at a time.',instructions:'Draft one cell on the 36 × 18 map, then lock your pin. Longitude wraps; latitude does not. Score uses grid distance, not kilometres. A hemisphere hint costs 100 points for that challenge. A pin within five grid steps qualifies. Equal scores use the seeded tie order.'},
 {id:'relic-auction',name:'Relic Auction',category:'Auction strategy',mode:'Sealed bids · game credits',color:'#f4b743',ink:'#29355c',description:'Spend game credits wisely. Collect relics. Complete a colourful set.',instructions:'Bid once or pass using virtual game credits. At the deadline the highest positive bid buys the relic at that price; others pay nothing. Equal bids use seeded seats rotated by auction index. Amber + jade + violet earns a set bonus. Only a relic owner with positive profit qualifies. Game credits have no wallet value.'},
] as const
