import {useEffect,useState} from 'react'
import type {Address} from 'viem'
import {heldNfts,type Nft} from './nftWallet'
import {explainError} from './api'
export function NftSelector({address,collection,selected,onSelect,disabled}:{address:string|null;collection:string;selected:string[];onSelect:(ids:string[])=>void;disabled:boolean}) {
 const [nfts,setNfts]=useState<Nft[]>([]),[manual,setManual]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{setNfts([]);setNotice('')},[address,collection])
 const load=async(ids:string[])=>{if(!address)return;setBusy(true);setNotice('Reading held NFTs…');try{const result=await heldNfts(address,collection as Address,ids);setNfts(result.nfts);setNotice(result.notice)}catch(e){setNotice(explainError(e))}finally{setBusy(false)}}
 return <section className="fr-nft-picker" aria-label="NFT selector"><p>Select one NFT or several distinct NFTs. Each selected ID becomes one prize for the displayed rank or recipient; every deposit uses this same pool.</p><button type="button" className="btn-ghost" disabled={disabled||busy||!address||!/^0x[0-9a-fA-F]{40}$/.test(collection)} onClick={()=>void load([])}>Read my held NFTs</button><label>Manual token IDs (for non-enumerable collections)<input value={manual} onChange={e=>setManual(e.target.value)} placeholder="7, 42, 100" /></label><button type="button" className="btn-ghost" disabled={disabled||busy||!address||!manual.trim()||!/^0x[0-9a-fA-F]{40}$/.test(collection)} onClick={()=>void load(manual.split(/[\s,]+/).filter(Boolean))}>Verify token IDs</button><p role="status">{notice||'Connect your creator wallet to read ownership. Reads are free; funding needs wallet transactions.'}</p><div className="fr-nft-grid">{nfts.map(nft=><label key={nft.tokenId}>{nft.image&&<img src={nft.image} alt={nft.name||`NFT #${nft.tokenId}`} loading="lazy" referrerPolicy="no-referrer"/>}<span>{nft.name||'NFT'} #{nft.tokenId}</span><input type="checkbox" checked={selected.includes(nft.tokenId)} disabled={disabled||busy} onChange={e=>onSelect(e.target.checked?[...selected,nft.tokenId]:selected.filter(id=>id!==nft.tokenId))}/></label>)}</div></section>
}
