// Curated modular imports. This file is reachable only through the lazy game route.
export {Engine} from '@babylonjs/core/Engines/engine'
export {Scene} from '@babylonjs/core/scene'
export {Vector3, Quaternion, Matrix} from '@babylonjs/core/Maths/math.vector'
export {Color3, Color4} from '@babylonjs/core/Maths/math.color'
export {ArcRotateCamera} from '@babylonjs/core/Cameras/arcRotateCamera'
export {UniversalCamera} from '@babylonjs/core/Cameras/universalCamera'
export {HemisphericLight} from '@babylonjs/core/Lights/hemisphericLight'
export {DirectionalLight} from '@babylonjs/core/Lights/directionalLight'
export {ShadowGenerator} from '@babylonjs/core/Lights/Shadows/shadowGenerator'
export {PBRMaterial} from '@babylonjs/core/Materials/PBR/pbrMaterial'
export {StandardMaterial} from '@babylonjs/core/Materials/standardMaterial'
export {DynamicTexture} from '@babylonjs/core/Materials/Textures/dynamicTexture'
export {RawCubeTexture} from '@babylonjs/core/Materials/Textures/rawCubeTexture'
export {Texture} from '@babylonjs/core/Materials/Textures/texture'
export {Mesh} from '@babylonjs/core/Meshes/mesh'
export {MeshBuilder} from '@babylonjs/core/Meshes/meshBuilder'
export {TransformNode} from '@babylonjs/core/Meshes/transformNode'
export {VertexData} from '@babylonjs/core/Meshes/mesh.vertexData'
export {VertexBuffer} from '@babylonjs/core/Buffers/buffer'
export {Animation} from '@babylonjs/core/Animations/animation'
export {AnimationGroup} from '@babylonjs/core/Animations/animationGroup'
export {LoadAssetContainerAsync} from '@babylonjs/core/Loading/sceneLoader'
export {Ray} from '@babylonjs/core/Culling/ray'
export {HavokPlugin} from '@babylonjs/core/Physics/v2/Plugins/havokPlugin'
export {PhysicsAggregate} from '@babylonjs/core/Physics/v2/physicsAggregate'
export {PhysicsShapeType} from '@babylonjs/core/Physics/v2/IPhysicsEnginePlugin'
export {PhysicsCharacterController, CharacterSupportedState} from '@babylonjs/core/Physics/v2/characterController'
export {SceneInstrumentation} from '@babylonjs/core/Instrumentation/sceneInstrumentation'
export type {AssetContainer, InstantiatedEntries} from '@babylonjs/core/assetContainer'
export type {AbstractMesh} from '@babylonjs/core/Meshes/abstractMesh'
import '@babylonjs/core/Physics/v2/physicsEngineComponent'
import '@babylonjs/core/Physics/joinedPhysicsEngineComponent'
import '@babylonjs/core/Lights/Shadows/shadowGeneratorSceneComponent'
import '@babylonjs/core/Rendering/utilityLayerRenderer'
import '@babylonjs/core/Meshes/thinInstanceMesh'
import '@babylonjs/loaders/glTF'
